# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4344e1899c8848c8186a537d4749d9f6e5b18a20e98c2c198bcebdc9e48116aa41a85ca00cc8790a2fdfd46fa476c0805a0656118ceb779343ab2cd0cc52ed5

test:
  secret_key_base: 5aa733142ac4217ff742176db91da9e099a5870d8907fb9081870478a5bded29cfe5860cf1450acbe1300c7abdb26c89134558166bd0f90369040b1077b6db05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
